const data = {
  products: [
    {
      brand: 'H&M',
      slug: '5-pack-slim-fit-T-shirts1',
      name: '5-pack Slim Fit T-shirts - White/Black - Men | H&M IE 3',
      description:
        'T-shirts in lightweight cotton jersey with a round, rib-trimmed neckline and a straight-cut hem. Slim fit that hugs the contours of your body, creating a fitted silhouette.',
      category: 'Men',
      type: 'Lifestyle',
      color: 'White',
      productImage: '/images/shirt.jpg',
      images: ['./images/.jpg', './images/.jpg', './images/.jpg'],
      sizes: ['X', 'XS', 'M', 'L', 'XL', 'XXL', 'XXXL'],
      price: 39.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      brand: 'H&M',
      slug: '5-pack-slim-fit-T-shirts2',
      name: '5-pack Slim Fit T-shirts - White/Black - Men | H&M IE 3',
      description:
        'T-shirts in lightweight cotton jersey with a round, rib-trimmed neckline and a straight-cut hem. Slim fit that hugs the contours of your body, creating a fitted silhouette.',
      category: 'Men',
      type: 'Lifestyle',
      color: 'White',
      productImage: '/images/shirt.jpg',
      images: ['./images/.jpg', './images/.jpg', './images/.jpg'],
      sizes: ['X', 'XS', 'M', 'L', 'XL', 'XXL', 'XXXL'],
      price: 39.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      brand: 'H&M',
      slug: '5-pack-slim-fit-T-shirts3',
      name: '5-pack Slim Fit T-shirts - White/Black - Men | H&M IE 3',
      description:
        'T-shirts in lightweight cotton jersey with a round, rib-trimmed neckline and a straight-cut hem. Slim fit that hugs the contours of your body, creating a fitted silhouette.',
      category: 'Men',
      type: 'Lifestyle',
      color: 'White',
      productImage: '/images/shirt.jpg',
      images: ['./images/.jpg', './images/.jpg', './images/.jpg'],
      sizes: ['X', 'XS', 'M', 'L', 'XL', 'XXL', 'XXXL'],
      price: 39.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      brand: 'H&M',
      slug: '5-pack-slim-fit-T-shirts4',
      name: '5-pack Slim Fit T-shirts - White/Black - Men | H&M IE 3',
      description:
        'T-shirts in lightweight cotton jersey with a round, rib-trimmed neckline and a straight-cut hem. Slim fit that hugs the contours of your body, creating a fitted silhouette.',
      category: 'Men',
      type: 'Lifestyle',
      color: 'White',
      productImage: '/images/shirt.jpg',
      images: ['./images/.jpg', './images/.jpg', './images/.jpg'],
      sizes: ['X', 'XS', 'M', 'L', 'XL', 'XXL', 'XXXL'],
      price: 39.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      brand: 'H&M',
      slug: '5-pack-slim-fit-T-shirts5',
      name: '5-pack Slim Fit T-shirts - White/Black - Men | H&M IE 3',
      description:
        'T-shirts in lightweight cotton jersey with a round, rib-trimmed neckline and a straight-cut hem. Slim fit that hugs the contours of your body, creating a fitted silhouette.',
      category: 'Men',
      type: 'Lifestyle',
      color: 'White',
      productImage: '/images/shirt.jpg',
      images: ['./images/.jpg', './images/.jpg', './images/.jpg'],
      sizes: ['X', 'XS', 'M', 'L', 'XL', 'XXL', 'XXXL'],
      price: 39.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      brand: 'H&M',
      slug: '5-pack-slim-fit-T-shirts6',
      name: '5-pack Slim Fit T-shirts - White/Black - Men | H&M IE 3',
      description:
        'T-shirts in lightweight cotton jersey with a round, rib-trimmed neckline and a straight-cut hem. Slim fit that hugs the contours of your body, creating a fitted silhouette.',
      category: 'Men',
      type: 'Lifestyle',
      color: 'White',
      productImage: '/images/shirt.jpg',
      images: ['./images/.jpg', './images/.jpg', './images/.jpg'],
      sizes: ['X', 'XS', 'M', 'L', 'XL', 'XXL', 'XXXL'],
      price: 39.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
  ],
};

module.exports = data;
